# Generated by Django 3.2.6 on 2023-03-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='link',
        ),
    ]
