# Generated by Django 3.2.6 on 2023-03-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_remove_episode_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='link',
            field=models.URLField(default='none'),
            preserve_default=False,
        ),
    ]
