# Generated by Django 4.1.7 on 2023-03-24 02:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcasts', '0003_episode_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='favorite',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
