# Generated by Django 4.1.7 on 2023-04-06 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_alter_episode_favorite_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Episode',
        ),
    ]
