# Generated by Django 4.1.7 on 2023-04-06 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcasts', '0006_delete_episode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('link', models.URLField()),
                ('image', models.URLField()),
                ('guid', models.CharField(max_length=50)),
                ('favorite', models.ManyToManyField(blank=True, default=None, related_name='episode_favorite', to=settings.AUTH_USER_MODEL)),
                ('podcast_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.content')),
            ],
        ),
    ]
