# Generated by Django 4.1.7 on 2023-04-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0010_alter_content_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='link',
        ),
        migrations.AddField(
            model_name='podcastcontent',
            name='link',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
